### PR TITLE
Fixes for devEnvSetup.js

### PR DESCRIPTION
**Pull request by dd137**
The script crashes due to
- .bin/npm not being available in all packages installed by devEnvSetup itself
- Trying to run tests for a meteor-desktop-localstorage package, even though that package isn't installed by devEnvSetup

The script also ignores the user's answer about whether to run tests or not (it always runs them, possibly after executing `finish()`). For convenience, it would also be nice to know what are the default answers to the script's questions.

This PR addresses these small problems, along with a rewrite of the related README section about "Developing meteor-desktop" and using devEnvSetup.

Note: The last two tests run by devEnvSetup, `npm run desktop -- build -b` and `npm run test-desktop` in meteor-desktop-test-app also fail, but I don't think this is caused by devEnvSetup itself and therefore is not addressed by this PR.

Tested with meteor-desktop 3.1.0.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@dd137 thank you for this PR. I think this is a general improvement over the existing situation, so unless you still want to add something I would like to merge this and then continue on from there.

**Comment by StorytellerCZ** [comment]
Changed the target towards the fix branch.

**Comment by StorytellerCZ** [comment]
@dd137 do you want to do anything more here.

**Comment by dd137** [comment]
@StorytellerCZ Thanks. I realized test-integration is missing from devEnvSetup.js. I'll add that with one more commit then I'm done here.

**Comment by dd137** [comment]
@StorytellerCZ Feel free to review and merge this PR. Thank you!

**Pull request merged**
