### PR TITLE
Fix bugs in 3.1

### LINKED ISSUE #12: Issues with 3.1.0 and Electron 14
Hey - I just installed 3.1.0, bumped Electron to 14.2.9 and ran Meteor update. Unfortunately I cannot build or start the app anymore. I'm getting back the following errors:

On build step: 
```
ERROR  electronApp:  error while transpiling or minifying:  TypeError: Invalid Version: undefined
    at new SemVer (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
    at compare (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
    at Function.lt (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
    at /Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/lib/index.js:275:15
    at /Users/max/Documents/GitHub/App/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12
    at ElectronApp.transpileAndMinify (/Users/max/Documents/GitHub/App/node_modules/@meteor-community/meteor-desktop/lib/electronApp.js:856:24)
    at ElectronApp.build (/Users/max/Documents/GitHub/App/node_modules/@meteor-community/meteor-desktop/lib/electronApp.js:451:24)
    at MeteorDesktop.buildInstaller (/Users/max/Documents/GitHub/App/node_modules/@meteor-community/meteor-desktop/lib/index.js:115:9)
```

On startup:
```
=> Errors prevented startup:                  
   
   While processing files with communitypackages:meteor-desktop-bundler (for target web.cordova):
   /Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11: Invalid Version: undefined
   at new SemVer (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
   at compare (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
   at Function.lt (/Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
   at /Users/max/Documents/GitHub/App/node_modules/@babel/preset-env/lib/index.js:275:15
   at /Users/max/Documents/GitHub/App/node_modules/@babel/helper-plugin-utils/lib/index.js:23:12
   at packages/meteor-desktop-bundler/bundler.js:815:28
   at Function.time (/Users/max/.meteor/packages/meteor-tool/.2.7.3.i3v35y.kfyte++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:284:12)
   at MeteorDesktopBundler.processFilesForTarget (packages/meteor-desktop-bundler/bundler.js:499:17)
```

### PR DESCRIPTION
**Pull request by StorytellerCZ**
This is a catch-all for bugs in 3.1 release.

Right now just a change from what was suggested in #12 done very quickly and probably wrong, but at least a starting point.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
The tests are failing, but at least they are now running fully.

**Comment by a4xrbj1** [comment]
> The tests are failing, but at least they are now running fully.

How can we execute the tests? Is that documented somewhere?

**Comment by StorytellerCZ** [comment]
@a4xrbj1 I'm going from the CircleCI definitions.

**Comment by dumski** [comment]
Hi, I'm trying to run simple-todos example as desktop app - no luck. I get the `Invalid Version: undefined` error. Is there any known workaround? I couldn't find any so far... Thanks

**Comment by StorytellerCZ** [comment]
Got the integration test running again. Next step is to fix the issues.

**Comment by dd137** [comment]
@StorytellerCZ The upgrade of node-fetch from v2 to v3 in 648c984, two commits earlier, breaks the tests. I pushed the fix directly here, hope that's ok for you.

**Comment by StorytellerCZ** [comment]
@dd137 I'm going to release 3.1.1 from what we currently have.

**Comment by StorytellerCZ** [comment]
One test still fails, but I think the progress has been good enough to merge this and get all the advancements out. Hopefully it can motivate more people to contribute.

**Comment by dd137** [comment]
> @dd137 I'm going to release 3.1.1 from what we currently have.

Great!

**Comment by StorytellerCZ** [comment]
After talking with @jankapunkt it will be `3.1.1-rc.0`

**Comment by StorytellerCZ** [comment]
Released v3.1.1-rc.0. On NPM you will have to use the `preview` tag or request the version directly to get it, same on Atmosphere.

**Comment by dd137** [comment]
Thanks @StorytellerCZ. There are a few issues:

### Tests
The tests now fail due to `error: no such version communitypackages:meteor-desktop-watcher@1.7.0` (& same for the bundler). Looking into the code, I think it's due to the combination of the RC version and a `process.env.PLUGIN_VERSION = '1.7.0';` in `integration.test.js`. I'll create a PR.

### Installing
`meteor npm i --save-dev @meteor-community/meteor-desktop@preview` leads to error `sh: babel: command not found`
Tried `meteor npm i --save-dev babel-cli` but then I get `> babel lib --out-dir dist --source-maps inline --copy-files` : `lib doesn't exist`.
Not sure what's up or how to reproduce locally. 3.1.0 didn't have this problem.

### Running
Installing the published commit but from a local directory doesn't have the above problem. However running Meteor I get `npm ERR! notarget No matching version found for winston@2.7.7.` The last winston@2 version is 2.4.7 so this is probably a typo. I will push a fix directly here.

**Comment by dd137** [comment]
Integration tests fail, probably when starting ChromeDriver:
```
INFO  meteorApp:  meteor build finished
INFO  electronApp:  built
Error: Failed to create session.
unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/runner/work/meteor-desktop/meteor-desktop/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.startWebDriverSession (/home/runner/work/meteor-desktop/meteor-desktop/node_modules/webdriver/build/utils.js:34:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Function.newSession (/home/runner/work/meteor-desktop/meteor-desktop/node_modules/webdriver/build/index.js:35:45)
    at Object.exports.remote (/home/runner/work/meteor-desktop/meteor-desktop/node_modules/webdriverio/build/index.js:53:22)
```

This does not happen on my macOS machine. Wondering if it's related to the OS - Ubuntu 22.04.3 LTS in this case.

**Comment by dd137** [comment]
I tested on a clean Ubuntu 22 install and the test works fine. Then I realized that while I took the test for granted, the Github action is quite new (created 2023-07)  and so possibly never worked as is. I'm wondering if the problem isn't that the CI test runs on a headless OS while [Electron needs a display to run](https://www.electronjs.org/docs/latest/tutorial/testing-on-headless-ci). If that is so, running the integration test with Xvfb or on macOS could solve the issue.

Any thoughts on this @StorytellerCZ? I might have a bit time for this tomorrow.

Also, do you have any idea about the `sh: babel: command not found` problem during installation I reported earlier? Do others encounter the same issue (cc @a4xrbj1)? (just run `meteor npm i --save-dev @meteor-community/meteor-desktop@preview` in a new Meteor project).

**Comment by StorytellerCZ** [comment]
@dd137 yes, you are correct on the tests. We moved them to GitHub from CircleCI as here they at least run, while on CircleCI they stopped working quiet a while ago.

**Comment by dd137** [comment]
@StorytellerCZ
**Tests:** Ok. I will look into the CI display thing and see if I can fix the issue this way.
**Installation:** Do you have any insight about the issue? Could it be related to how the package was published? I don't understand why the build script (`babel lib --out-dir dist --source-maps inline --copy-files`) gets triggered. It wasn't with the previous version 3.1.0. Not sure how I can test/investigate this locally. Thanks

**Comment by StorytellerCZ** [comment]
Since we are now passing, I would like to release another rc or maybe as a final 3.1.1. Thoughts?

**Comment by jankapunkt** [comment]
@StorytellerCZ I would suggest another rc, I wanted to test this tomorrow by making one of our apps "desktop-ready" with this package. From what I understand I don't need Android or iOS but only this package and a .desktop folder with the correct config. Or do you think this is too big for my plan?

**Comment by StorytellerCZ** [comment]
`rc.1` released

**Comment by StorytellerCZ** [comment]
RC 2 is out!

**Comment by dd137** [comment]
> From what I understand I don't need Android or iOS but only this package and a .desktop folder with the correct config. Or do you think this is too big for my plan?

@jankapunkt In case you're still wondering, that's correct. In my experience, a simple `echo "ios" >> .meteor/platforms` is enough for MD to work. And the .desktop folder will be auto-generated by `meteor npm run desktop -- init`. All-in-all, it shouldn't be difficult. See the [updated quick-start guide](https://github.com/Meteor-Community-Packages/meteor-desktop/tree/fix/bug-12#quick-start) for more info. Would be nice to have your feedback.

**Comment by StorytellerCZ** [comment]
Anyone has any significant issues with rc.2? If not then I'm going to do a full release this weekend or early next week.

**Comment by a4xrbj1** [comment]
> Anyone has any significant issues with rc.2? If not then I'm going to do a full release this weekend or early next week.

It's been running fine locally. I haven't pushed a new version to users but would appreciate if you go ahead and release a new version.

**Pull request merged**
