### PR TITLE
feature/update electron to 11.5

### PR DESCRIPTION
**Pull request by arty-ms**
## What
Updated electron version to 11.5.0 based on the work done in (https://github.com/Meteor-Community-Packages/meteor-desktop/pull/8). And after testing it in dev, found issue with `makeSingleInstance` - TypeError: app.makeSingleInstance is not a function. Method makeSingleInstance was deprecated since electron 4.0. https://www.electronjs.org/docs/latest/breaking-changes#appmakesingleinstance.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
@arty-ms @marozartsem9 thank you very much! I will merge this into the Electron 11 branch and see if we can move forward with it.

**Comment by a4xrbj1** [comment]
I’m running electron version 11.5 for a while now, without any problems. So this bug must be triggered by a specific configuration, good that we found it.

Do you have any outline/plans to go beyond version 11.5, Jan?

**Comment by StorytellerCZ** [comment]
Already looking into going to Electron 14, which is as far that we can go with the current Meteor so that Node versions are in sync:
https://github.com/Meteor-Community-Packages/meteor-desktop/pull/11

I do recall there were some issues with going that far, but I will have to dive into it. But to do that properly it looks like the integrations tests will have to be re-written and probably more as well.

Once Meteor goes to Node 16+ then I will start looking into upgrading to the appropriate Electron version.

**Comment by a4xrbj1** [comment]
Thanks @StorytellerCZ for that update.

I did get a notification by Snyk that there's a security risk in our current Meteor-desktop 3.0.1 due to a vulnerability in lodash 4.17.15

Here are the issues as per Snyk:

https://snyk.io/vuln/SNYK-JS-LODASH-1018905

https://snyk.io/vuln/SNYK-JS-LODASH-1040724

https://snyk.io/vuln/SNYK-JS-LODASH-608086

So instead of me just fixing this locally in my private repo, it makes more sense to fix it in this repo, right?

However, I have no clue on what the "normal" procedure is to raise that. Do I need to create an issues in this repo? Please advise as I'm still learning. Thanks, Jan!

**Comment by StorytellerCZ** [comment]
If you have the fix, the best thing would be to open a Pull request with it.

**Pull request merged**
