### PR TITLE
fix: do not download new version when desktopHCP is set to false

### PR DESCRIPTION
**Pull request by mjcctech**

### CODE REVIEW

**Review by a4xrbj1 — APPROVED** [review]
Looks good to me, thanks

**Comment by a4xrbj1** [comment]
I've run the proposed changes but unfortunately both the unit tests as well as the integration tests fail. Could any of you @mjcctech or @StorytellerCZ take a look at why the tests are failing? Is there a problem with the proposed code changes or is it rather a problem with the tests itself (I know some improvements was done recently to them).

I also noticed that we're running Meteor 2.6 for it, shouldn't we upgrade this to the most recent version (2.13) or at least the less problematic 2.12 version (due to changing node on 2.13)?

I hope I didn't do anything wrong here or not following standards. This is the first time I ever get engaged on such requests, please let me know and I will take your feedback into account. Thanks!

**Comment by mjcctech** [comment]
I fixed functional test. Integration test were failing before and not sure how to fix them. Seems to be issue with [mockery](https://www.npmjs.com/package/mockery)

**Comment by a4xrbj1** [comment]
> I fixed functional test. Integration test were failing before and not sure how to fix them. Seems to be issue with [mockery](https://www.npmjs.com/package/mockery)

I get the following error from the integration test:

```
TypeError: dest.end is not a function
    at Socket.onend (internal/streams/readable.js:670:10)
    at Object.onceWrapper (events.js:519:28)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[1691760343.130][INFO]: [9f13e1f6a41b662ad4c16830ace94aaa] RESPONSE InitSession ERROR unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/runner/work/meteor-desktop/meteor-desktop/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

I'm not familiar with this testing script and never encountered such an error, sorry

**Review by StorytellerCZ — APPROVED** [review]
LGTM, thanks for the extra test.
As for the integration tests, that if I remember correctly is an issue with the test runner. Any PRs for this welcome, but I won't hold them failing against this PR.

**Comment by StorytellerCZ** [comment]
As for releasing this, we will have to get over the broken tests if possible. If you need it asap, then I'll get together a new version with what we have.

**Comment by a4xrbj1** [comment]
> As for releasing this, we will have to get over the broken tests if possible. If you need it asap, then I'll get together a new version with what we have.

I certainly would appreciate if we could release this fix soon. I'm having problems with the app even though I turned desktopHCP to false and it still tries to download files, complains about not finding them and in some cases, the app becomes unusable until it's being removed and installed fresh.

Thanks

**Comment by StorytellerCZ** [comment]
I'll try to get it done this weekend, but no promises.

**Comment by StorytellerCZ** [comment]
@a4xrbj1 which version are you currently using?

**Comment by a4xrbj1** [comment]
> which version are you currently using?

Not sure what you refer to so will try a few:

Meteor version 2.12
NodeJS 14.21.3
Meteor-Desktop 3.01
Electron: 11.5.0
Electron-Updater: 5.0.5
Electron-Builder: 23.1.0
Electron-Packager: 17.1.1
Electron-Rebuild: 3.2.9

**Comment by ramijarrar** [comment]
@StorytellerCZ The code here actually disables the Meteor hot code push mechanism which should not be affected by the `desktopHCP` setting (this only relates to the experimental `.desktop` hot code push).

This should be reverted as it represents a major regression.

**Comment by met5678** [comment]
> @StorytellerCZ The code here actually disables the Meteor hot code push mechanism which should not be affected by the `desktopHCP` setting (this only relates to the experimental `.desktop` hot code push).
> 
> This should be reverted as it represents a major regression.

+1 on this. I just upgraded Meteor desktop and Meteor's hot code reload no longer works. I have always had `desktopHCP` set to false because it's never worked for me, but now I don't even get regular renderer-side reloads.

**Comment by a4xrbj1** [comment]
> just upgraded Meteor desktop and Meteor's hot code reload no longer works. I have always had `desktopHCP` set to false because it's never worked for me, but now I don't even get regular renderer-side reloads.

Please note that if you're using Meteor 3.4.x you should use my modernized package of meteor-desktop (see https://github.com/a4xrbj1/meteor-desktop) - this one here is a dead end or a dead horse beaten too many times, whichever you prefer.

I've put several days of work into modernizing the package it was just updated 1h ago.

**Pull request merged**
