### PR TITLE
Electron 11

### PR DESCRIPTION
**Pull request by StorytellerCZ**
This is an attempt to upgrade Electron to version 11.5.0 and other dependencies as a first step in modernizing this package. 

Feedback and testing welcome!

### CODE REVIEW

**Comment by diavrank** [comment]
Hi @StorytellerCZ , how can we install this version of your PR in my machine? or is there a test version on npmjs?

**Comment by diavrank** [comment]
maybe this [repo](https://github.com/sharekey/meteor-desktop) can be helpful

**Comment by StorytellerCZ** [comment]
@diavrank as you can see the tests are failing, but that has been documented elsewhere as a failure of the tests. I will try to get a beta release out for testing anyhow sometime today or tomorrow. Feel free to bug me about this if it does not happen.

**Comment by diavrank** [comment]
@StorytellerCZ hi, is there any update on this? :)

**Comment by StorytellerCZ** [comment]
Looks like the entire testing suite needs to undergo severe upgrade. Done some limited testing myself, but would appreciate more feedback.

**Pull request merged**
