### PR TITLE
Update skeleton dependencies patch and some feature releases #31

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Review by a4xrbj1 — APPROVED** [review]

**Comment by a4xrbj1** [comment]
@StorytellerCZ - I have Winston at version 3.3.0 (first version with Node 14) and it works fine it seems (I haven't tested it on Production, so I'm not able to see if the logging still works fine with DataDog which is my aggregator of log files.

I couldn't find version 2.7.7 though.

Also note that I'm still using reify 0.17.3 and not meteor/reify - but again no problems with the app from the limited testing I did.

**Comment by a4xrbj1** [comment]
@dd137 - in regards to your comment that this package.json is only used for the skeleton app. Can confirm that however starting my app with the debug option shows that the `electronAppScaffold` is overwriting any changes and reverts to the original values:

`VERBOSE  meteorApp:  updating .meteor/.gitignorez`
`VERBOSE  meteorApp:  desktopHCP is not enabled, removing required packages`
`VERBOSE  electronAppScaffold:  clearing desktop-build`
`VERBOSE  electronAppScaffold:  creating /Users/andreaswest/Documents/workspace/frontend/.meteor/desktop-build/app`
`VERBOSE  electronAppScaffold:  copying skeleton app`
`VERBOSE  electronAppScaffold:  writing package.json`
`VERBOSE  electronApp:  updating package.json fields`
`DEBUG  electronApp:  writing updated package.json`
`INFO  electronApp:  updating list of package.json's dependencies`
`DEBUG  electronApp:  merging settings.json[dependencies]`
`DEBUG  electronApp:  merging settings.json[plugins]`
`DEBUG  electronApp:  merging dependencies from modules`
`DEBUG  electronApp:  writing updated package.json`
`VERBOSE  electronApp:  calculating compatibility version`
`DEBUG  electronApp:  meteor-desktop compatibility version is  3`
`DEBUG  electronApp:  .desktop compatibility version is  3`
`INFO  electronApp:  issuing node_modules install from electron-builder`

**Comment by a4xrbj1** [comment]
Integration test fails here:

=> Errors while parsing arguments:

While adding package communitypackages:meteor-desktop-watcher@=1.7.0:
error: no such version communitypackages:meteor-desktop-watcher@1.7.0

While adding package communitypackages:meteor-desktop-bundler@=1.7.0:
error: no such version communitypackages:meteor-desktop-bundler@1.7.0

ERROR  electronApp:  error while checking for required packages:  Error: Error: adding packages failed
    at MeteorApp.ensureDesktopHCPPackages (/home/runner/work/meteor-desktop/meteor-desktop/lib/meteorApp.js:83:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at ElectronApp.build (/home/runner/work/meteor-desktop/meteor-desktop/lib/electronApp.js:316:13)
    at MeteorDesktop.build (/home/runner/work/meteor-desktop/meteor-desktop/lib/index.js:131:9)
    at Context.<anonymous> (/home/runner/work/meteor-desktop/meteor-desktop/tests/integration/integration.test.js:239:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @meteor-community/meteor-desktop@3.1.1-rc.0 test-integration: `mocha -t 10000 -r @meteorjs/reify "tests/+(integration)/**/*.test.js"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @meteor-community/meteor-desktop@3.1.1-rc.0 test-integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-10-04T15_35_13_451Z-debug.log
Error: Process completed with exit code 1.

I'm not running HCP as it was causing errors with my app, so no idea what's wrong here.

**Comment by dd137** [comment]
Ah, I just noticed some of the same problems (https://github.com/Meteor-Community-Packages/meteor-desktop/pull/13#issuecomment-1748450031).

@a4xrbj1 I see. Looks indeed like package.json is rewritten every time. That explain you initial observation. Let's update the dependencies in skeletonDependencies.js, as per this PR and your issue 👍

**Pull request merged**
